### ISSUE TITLE
Research how to switch SQLite db connection when we switch projects

### ISSUE THREAD

**Issue by baali** [brightway-lca/bw_projects#2]
Based on the comment:

> when we change projects, we disconnect the sqlite_lci_db object from one SQLite database (file), and attach it to another one. This is tricky because it currently works fine, but after projects is stripped out bw2data (and hence sqlite_lci_db) doesn't know that the project has switched. You probably also saw that there are some other JSON or pickle files which also need to be re-read, but we are switching towards storing everything in the SQLite database. So I think there has to be some hook in bw2data which is called when the user_data_dir is changed, and another for the logs directory.

Related to https://github.com/brightway-lca/brightway2-data/issues/98

**Comment by cmutel** [comment]
There are two main SQLite databases to be aware of:

1. A database which stores information about `projects`. This we keep and port to `bw_projects`. `bw_projects` also therefore needs to use `appdirs` to know what directory this database is stored in.
2. A database which has project-specific data. This is the database which make life tricky - to allow `bw2database.Database` (a Peewee Model) to *just work* when we switch projects, we [defer the binding of the Peewee model](https://docs.peewee-orm.com/en/latest/peewee/database.html#deferring-initialization), and the [use the `SubstitutableDatabase` class](https://github.com/baali/bw_projects/blob/main/bw2projects/sqlite.py) to allow us to dynamically switch the SQLite database file. 

In the future, `bw2data` will try to import `bw_projects`, and then add the substitutable database from the second item to a registry of databases *in bw_projects* which need to be modified when `switch` (currently `set_current`, but I like `switch` or something similar more) is called.

**Comment by baali** [comment]
Existing solution using `[SubstitutableDatabase](https://github.com/baali/bw_projects/blob/main/bw2projects/sqlite.py)` works. We need to evaluate or follow up on is this the best approach and if there are more options available.

**Comment by cmutel** [comment]
We don't need to solve things for other libraries building on `bw_projects`, we will execute the registered callbacks, the other libraries are responsible for their behaviour.
